-- RCM 통제 마스터 시딩
-- 402건 (중복 제거 후)
-- 생성: 2026-05-29

INSERT INTO rcm_controls (ctrl_code, ctrl_title, ctrl_type, ctrl_method, frequency, it_dep, system_name, evidence, ctrl_kind)
VALUES
  ('FR-C-1-1-1', '회계기준 제∙개정사항 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '회계기준 제ㆍ개정 사항 검토 자료', 'PLC'),
  ('FR-C-1-1-2', '회계정책 변경사항에 대한 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '회계기준 제ㆍ개정 사항 검토 자료', 'PLC'),
  ('FR-C-1-1-3', '회계정책 변경사항 공지', 'Preventive', 'Manual', 'Annually', 'N', '', '회계정책 사내공지내역', 'PLC'),
  ('FR-C-1-1-4', '한국채택국제회계기준 개정 사항에 대한 주기적인 교육', 'Preventive', 'Manual', 'Annually', 'N', '', '회계팀 연간교육계획서', 'PLC'),
  ('FR-C-1-2-1', '계정과목정보 생성/변경에 대한 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '계정과목 생성/변경 요청 List', 'PLC'),
  ('FR-C-1-2-2', '계정과목 생성/변경에 대한 권한 제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-기본정보-계정과목관리', 'ERP 프로그램 별 사용자 권한 리스트', 'PLC'),
  ('FR-C-1-2-3', '계정과목 이중생성 제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-기본정보-계정과목관리', '기존 계정과목 코드로 신규계정 생성이 불가능함을 확인할 수 있는 화면 캡쳐', 'PLC'),
  ('FR-C-1-2-4', '사용중단 계정과목 입력 제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-기본정보-계정과목관리, 
ERP 회계관리-전표-전표 등록-일반전표, 
ERP 회계관리-장부관리-원장관리-계정별 원장', '사용중단계정으로 전표입력되지 않음을 확인할 수 있는 화면 캡쳐', 'PLC'),
  ('FR-C-1-3-1', '전표승인절차', 'Detective', 'Manual', 'Event driven', 'N', '', '확정전표의 실물전표', 'PLC'),
  ('FR-C-1-3-2', '부서별 통제성과목 전표생성한도 관리', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-전표-전표 등록-일반전표, 
ERP 회계관리-예산관리-예산집행현황', '전표 생성 오류 화면캡쳐', 'PLC'),
  ('FR-C-1-4-1', '결산 절차 체크리스트 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', '결산 Checklist', 'PLC'),
  ('FR-C-1-4-2', 'ERP 전표 마감 이후 입력 전표에 대한 검토 및 승인', 'Detective', 'Manual', 'Monthly', 'N', '', 'ERP 전표 확정내역 리스트', 'PLC'),
  ('FR-C-1-4-3', 'ERP 전표마감 기능 권한 관리', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-전표-전표마감일자 확정', 'ERP 전표마감일자 확정 권한자 List', 'PLC'),
  ('FR-C-1-4-4', '미결잔액에 대한 관리', 'Preventive', 'Manual', 'Quarterly', 'N', '', '장기미처리계정잔액 현황', 'PLC'),
  ('FR-C-1-4-5', '매년 손상징후에 대한 검토', 'Preventive', 'Manual', 'Annually', 'N', '', '손상징후 검토 Checklist', 'PLC'),
  ('FR-C-1-4-6', '매년 말 CGU의 적정성 및 변동 여부에 대한 검토 수행', 'Preventive', 'Manual', 'Annually', 'N', '', 'CGU 검토 Checklist', 'PLC'),
  ('FR-C-1-4-7', '손상징후 발견 시 손상검사 수행 후 상위권자의 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '자산손상 검토 Checklist', 'PLC'),
  ('FR-C-1-4-8', '투자주식 손상검토 결과에 대한 상위 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '투자주식 손상검토 Checklist', 'PLC'),
  ('FR-C-1-4-9', '외화환산 결산전표입력 사항의 검토 및 승인', 'Detective', 'Manual', 'Quarterly', 'N', '', '외화평가 수기전표', 'PLC'),
  ('FR-C-1-4-10', '선급비용 자동계산 전산통제', 'Preventive', 'Automated', 'Quarterly', 'Y', 'ERP 회계관리-장부관리-결산관리-선급비용, 선급비용 자동전표', 'ERP 선급비용 자동전표 계산 처리 화면', 'PLC'),
  ('FR-C-1-5-1', '결산명세서에 대한 적정성 검토', 'Preventive', 'Manual', 'Quarterly', 'N', '', '결산부속명세서 및 승인내역', 'PLC'),
  ('FR-C-1-5-2', '공시사항점검표에 대한 검토 및 승인', 'Detective', 'Manual', 'Annually', 'N', '', '공시사항점검표', 'PLC'),
  ('FR-C-1-5-3', '최종결산조정분개의 최종재무제표 및 부속명세서에 대한 적절한 반영', 'Preventive', 'Manual', 'Quarterly', 'N', '', '별도재무제표정산표(WTB파일)', 'PLC'),
  ('FR-C-1-5-4', '주석 작성사항에 대한 현업부서의 검토 및 승인', 'Detective', 'Manual', 'Quarterly', '', '', '현업부서로부터 수령한 주석작성 기초자료', 'PLC'),
  ('FR-C-1-5-5', '주석 검토 파일(결산 Package) 관리', 'Detective', 'Manual', 'Quarterly', 'N', '', '주석 검토 파일(결산 Package)', 'PLC'),
  ('FR-C-1-5-6', '특수관계자 리스트에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '특수관계자 리스트 및 승인내역', 'PLC'),
  ('FR-C-1-5-7', '특수관계자 주석 적정성 검토', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 회계관리-장부관리-잔액관리-거래처별 잔액', '특수관계자 주석 Checklist', 'PLC'),
  ('FR-C-1-5-8', '보고기간 후 사건에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '보고기간후 사건 검토내역', 'PLC'),
  ('FR-C-1-5-9', '현금흐름표에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '현금흐름표 Checklist', 'PLC'),
  ('FR-C-1-5-10', '재무제표 및 주석에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '재무제표 및 주석 검토내역', 'PLC'),
  ('FR-C-1-5-11', '사전재무제표와 최종재무제표 차이 원인 검토 및 승인', 'Detective', 'Manual', 'Annually', 'N', '', '최종재무제표 검토 보고내역', 'PLC'),
  ('TX-C-1-1-1', '조세법령 개정사항 검토 및 보고', 'Preventive', 'Manual', 'Annually', 'N', '', '개정세법 검토 문서(국세청 책자 등)', 'PLC'),
  ('TX-C-1-2-1', '법인세비용, 미지급법인세, 이연법인세에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '법인세비용 및 이연법인세 Checklist', 'PLC'),
  ('TX-C-1-2-2', '법인세 신고 및 납부에 대한 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '1.법인세 납부전표 및 증빙', 'PLC'),
  ('TX-C-1-3-1', '법인지방세 안분내역 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '법인지방소득세 안분내역', 'PLC'),
  ('TX-C-1-4-1', '부가세 오류 내역 검토', 'Preventive', 'Manual', 'Monthly', 'N', '', '홈텍스 전자세금계산서리스트', 'PLC'),
  ('TX-C-1-4-2', '부가세 신고 및 납부관련 신고', 'Preventive', 'Manual', 'Quarterly', 'N', '', '부가세 신고 전표 및 첨부파일', 'PLC'),
  ('TX-C-1-5-1', '원천세신고납부에 대한 승인', 'Preventive', 'Manual', 'Monthly', 'N', '', '원천세 신고 및 납부전표', 'PLC'),
  ('DC-C-1-1-1', '공시 관련법규 및 규정 개정', 'Preventive', 'Manual', 'Annually', 'N', '', '공시관리규정 또는 지침', 'PLC'),
  ('DC-C-1-1-2', '모든 공시내역은 권한있는자에 의해 정확하게 공시', 'Preventive', 'Manual', 'Annually', 'N', '', 'Dart 전송권한의 부여내역', 'PLC'),
  ('DC-C-1-1-3', '공시자료 검토 및 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '공시자료 검토내역', 'PLC'),
  ('DC-C-1-2-1', '공시관련 기초정보에 대한 검토 및 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '발행공시자료', 'PLC'),
  ('DC-C-1-2-2', '최종공시사항에 대한 검토 및 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '발행공시자료', 'PLC'),
  ('FA-C-1-1-1', 'ERP 고정자산관리 신규 등록/변경/폐기 권한부여', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-고정자산관리-기본등록', 'ERP 프로그램 별 사용자 권한 리스트', 'PLC'),
  ('FA-C-1-1-2', 'ERP 고정자산관리 고정자산 정보 등록 및 변경 등록 승인', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 회계관리-고정자산관리-기본등록-등록승인', 'ERP 고정자산 등록승인에서 평가 대상기간동안을 조회한 화면 캡쳐', 'PLC'),
  ('FA-C-1-2-1', '사업계획에 따라 편성된 주요투자계획 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '샘플로 추출된 고정자산 취득건의 승인된 투자예산계획서', 'PLC'),
  ('FA-C-1-2-2', '고정자산 취득 품의서 승인


', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 고정자산 취득 관련 품의서', 'PLC'),
  ('FA-C-1-2-3', '고정자산 취득 전표 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 추출된 고정자산 취득 승인 전표 및 증빙', 'PLC'),
  ('FA-C-1-2-4', '건설중인자산계정의 본계정 대체 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 추출된 건설중인자산 본계정 대체 승인 전표 및 증빙', 'PLC'),
  ('FA-C-1-3-1', '고정자산의 유지보수 및 추가취득 내역 검토 및 승인

', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인을 득한 고정자산 수리 신청문서', 'PLC'),
  ('FA-C-1-3-2', '고정자산 정기실사 관련 보고 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '고정자산 실사보고서', 'PLC'),
  ('FA-C-1-4-1', '고정자산 처분의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '고정자산 처분 관련 승인된 전표 및 품의서', 'PLC'),
  ('FA-C-1-4-2', '회계팀의 고정자산 처분손익 검토 및 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '고정자산 처분 전표 및 손익 검토 내역 확인 가능한 품의서', 'PLC'),
  ('FA-C-1-5-1', 'ERP 감가상각비 자동계산 전산통제', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 회계관리-고정자산관리-감가상각계산', 'ERP상 감가상각비 계산 내역 화면', 'PLC'),
  ('FA-C-1-5-2', 'ERP 감가상각비 자동 비용배부 전산통제', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 회계관리-고정자산관리-기본등록', 'ERP상 감가상각비 계산 내역 배부 화면', 'PLC'),
  ('FA-C-1-5-3', '감가상각비 계산시 적용되는 회계추정 정보 검토', 'Preventive', 'Manual', 'Annually', 'N', '', '검토 보고서상 내용연수 등 적정성 검토내역 확인', 'PLC'),
  ('FA-C-1-5-4', '고정자산 명세서 작성 및 ERP 고정자산대장 대사 검토', 'Detective', 'Manual', 'Monthly', 'N', '', 'ERP상 고정자산대장 기본 정보 화면 (취득/처분 내역 반영분)', 'PLC'),
  ('FA-C-1-6-1', '임대차계약 리스트의 완전성 검토 및 승인', 'Detective', 'Manual', 'Quarterly', 'N', '', '회계팀장 승인을 득한 리스관련 손익계정 완전성 검토 내역, 이를 승인받은 결재문서', 'PLC'),
  ('FA-C-1-6-2', '리스부채 산정시 활용되는 기초 계약정보의 정확성과 회계처리의 적정성 검토 및 승인', 'Detective', 'Manual', 'Quarterly', 'N', '', '리스계약분석서', 'PLC'),
  ('FA-C-1-6-3', '할인율의 적정성 검토 및 승인', 'Detective', 'Manual', 'Quarterly', 'N', '', '증분차입이자율 회사계산 검토 내역 (대상 차입금과 기준 결산일의 재무상태표상 차입금 잔액 대사내역 등)', 'PLC'),
  ('FA-C-1-7-1', '임대자산 취득(대체) 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '분기별 작성되는 임대자산 명세서', 'PLC'),
  ('FA-C-1-7-2', '임대자산 현장의 시공진행에 따른 회수계획 문서화', 'Preventive', 'Manual', 'Monthly', 'N', '', '승인된 임대자산 회수계획서', 'PLC'),
  ('FA-C-1-7-3', '임대자산 입고 및 출고물량 차이내역 분석 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '입고리스트와 출고리스트간 차이내역을 대사한 정산의뢰서', 'PLC'),
  ('FA-C-1-7-4', '외주업체의 보수비(임대 외주가공비) 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '임대-외주가공비 승인된 전표', 'PLC'),
  ('FA-C-1-7-5', '회수된 임대자산에 대해 처분/폐기 문서 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '임대자산 폐기/처분 전표', 'PLC'),
  ('FA-C-1-7-6', '임대자산 감가상각비 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '분기별 임대자산 감가상각 명세서 (감가상각 대상 정보와 ERP 입력정보간 대사된 내역 포함)', 'PLC'),
  ('FA-C-1-7-7', '임대자산 명세서 기말 중량(수량) 검토 ', 'Detective', 'Manual', 'Annually', 'N', '', '기말 임대자산 명세서와 대사된 실제중량(수량) 검토내역', 'PLC'),
  ('PP-C-1-1-1', '신규 구매업체 선정 시 선정기준에 따른 선정', 'Preventive', 'Manual', 'Event driven', 'N', '', 'ERP상 신규 등록된 거래처 중 구매담당자 등록 List', 'PLC'),
  ('PP-C-1-1-2', '구매업체에 대한 주기적 평가', 'Detective', 'Manual', 'Annually', 'N', '', '발주완료된 구매업체(신규 업체 제외) List', 'PLC'),
  ('PP-C-1-1-3', 'ERP 구매업체 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', 'ERP 사용권한리스트', 'PLC'),
  ('PP-C-1-1-4', 'ERP 구매업체 정보 변경 시 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 구매업체에 대한 거래계좌 등록(변경) 신청서', 'PLC'),
  ('PP-C-1-1-5', 'ERP 구매업체 정보 생성/변경항목과 등록/변경품의서 간 대사', 'Detective', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리-기본정보-거래처관리', '샘플로 선정한 분기에 대한 ERP 거래처 정보 변경 현황과 거래계좌 등록(변경) 신청서 간 대사내역', 'PLC'),
  ('PP-C-1-1-6', 'ERP 구매업체 등록시 필수정보가 입력되지 않으면 신규 거래처를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-1-2-1', '구매청구서에 대한 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 승인된 구매청구서', 'PLC'),
  ('PP-C-1-2-2', '구매발주서에 대한 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 승인된 구매발주서', 'PLC'),
  ('PP-C-1-2-3', '구매발주서는 필수정보가 누락없이 작성되어 일련번호로 문서화됨', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 생산관리-구매관리-발주서 등록', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-1-2-4', '장기미발주 현황 모니터링', 'Detective', 'ITDM', 'Monthly', 'Y', 'ERP2 생산관리-구매관리-발주서 현황', '샘플로 선정한 월에 대한 구매발주현황자료', 'PLC'),
  ('PP-C-1-2-5', '종결된 구매주문에 대하여 발주가 불가능함', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 생산관리-구매관리-발주서 등록', '구매발주서 등록시 구매요청서(청구번호) 등록한 화면 캡쳐본', 'PLC'),
  ('PP-C-1-2-6', '납기일자를 초과한 구매발주에 대한 모니터링', 'Detective', 'ITDM', 'Monthly', 'Y', 'ERP2 생산관리-구매관리-발주서 현황', '샘플로 선정한 월에 대한 구매발주현황자료', 'PLC'),
  ('PP-C-1-2-7', 'ERP 자재 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-품목관리', 'ERP 자재 마스터 상 자재정보 생성 및 변경 권한자 List', 'PLC'),
  ('PP-C-1-2-8', 'ERP 자재 정보 등록 시 필수정보가 입력되지 않으면 신규 자재를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-품목관리', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-1-2-9', '승인된 구매발주서 없이 입고처리 불가', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 생산관리-구매관리-입고관리', '자재 입고처리 시 구매발주서를 선택하지 않으면 입고처리가 되지 않음을 확인한 화면 캡쳐', 'PLC'),
  ('PP-C-1-3-1', '지급채무전표 생성시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '지급채무(외상매입금, 미지급금)전표 실물전표', 'PLC'),
  ('PP-C-2-1-1', '신규 구매업체 선정 시 선정기준에 따른 선정', 'Preventive', 'Manual', 'Event driven', 'N', '', 'ERP상 신규 등록된 거래처 중 구매담당자 등록 List', 'PLC'),
  ('PP-C-2-1-2', '구매업체에 대한 주기적 평가', 'Detective', 'Manual', 'Annually', 'N', '', '발주완료된 구매업체(신규 업체 제외) List', 'PLC'),
  ('PP-C-2-1-3', 'ERP 구매업체 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', 'ERP 사용권한리스트', 'PLC'),
  ('PP-C-2-1-4', 'ERP 구매업체 정보 변경 시 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 구매업체에 대한 거래계좌 등록(변경) 신청서', 'PLC'),
  ('PP-C-2-1-5', 'ERP 구매업체 정보 생성/변경항목과 등록/변경품의서 간 대사', 'Detective', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리-기본정보-거래처관리', '샘플로 선정한 분기에 대한 ERP 거래처 정보 변경 현황과 거래계좌 등록(변경) 신청서 간 대사내역', 'PLC'),
  ('PP-C-2-1-6', 'ERP 구매업체 등록시 필수정보가 입력되지 않으면 신규 거래처를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-2-2-1', '구매청구서에 대한 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 승인된 구매청구서', 'PLC'),
  ('PP-C-2-2-2', '구매발주서에 대한 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 승인된 구매발주서', 'PLC'),
  ('PP-C-2-2-3', '구매발주서는 필수정보가 누락없이 작성되어 일련번호로 문서화됨', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-발주서 등록', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-2-2-4', '장기미발주 현황 모니터링', 'Detective', 'ITDM', 'Monthly', 'Y', 'ERP 생산관리-자재구매관리-발주서 현황', '샘플로 선정한 월에 대한 구매발주현황자료', 'PLC'),
  ('PP-C-2-2-5', '종결된 구매주문에 대하여 발주가 불가능함', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-발주서 등록', '구매발주서 등록시 구매요청서(청구번호) 등록한 화면 캡쳐본', 'PLC'),
  ('PP-C-2-2-6', '납기일자를 초과한 구매발주에 대한 모니터링', 'Detective', 'ITDM', 'Monthly', 'Y', 'ERP 생산관리-자재구매관리-발주서 현황', '샘플로 선정한 월에 대한 구매발주현황자료', 'PLC'),
  ('PP-C-2-2-7', 'ERP 자재 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-품목관리', 'ERP 자재 마스터 상 자재정보 생성 및 변경 권한자 List', 'PLC'),
  ('PP-C-2-2-8', 'ERP 자재 정보 등록 시 필수정보가 입력되지 않으면 신규 자재를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-품목관리', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-2-2-9', '승인된 구매발주서 없이 입고처리 불가', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-입고관리', '자재 입고처리 시 구매발주서를 선택하지 않으면 입고처리가 되지 않음을 확인한 화면 캡쳐', 'PLC'),
  ('PP-C-2-3-1', '지급채무전표 생성시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '지급채무(외상매입금, 미지급금)전표 실물전표', 'PLC'),
  ('PP-C-3-1-1', '신규 구매업체 선정 시 선정기준에 따른 선정', 'Preventive', 'Manual', 'Event driven', 'N', '', 'ERP상 신규 등록된 거래처 중 구매담당자 등록 List', 'PLC'),
  ('PP-C-3-1-2', '구매업체에 대한 주기적 평가', 'Detective', 'Manual', 'Annually', 'N', '', '발주완료된 구매업체(신규 업체 제외) List', 'PLC'),
  ('PP-C-3-1-3', 'ERP 구매업체 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', 'ERP 사용권한리스트', 'PLC'),
  ('PP-C-3-1-4', 'ERP 구매업체 정보 변경 시 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 구매업체에 대한 거래계좌 등록(변경) 신청서', 'PLC'),
  ('PP-C-3-1-5', 'ERP 구매업체 정보 생성/변경항목과 등록/변경품의서 간 대사', 'Detective', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리-기본정보-거래처관리', '샘플로 선정한 분기에 대한 ERP 거래처 정보 변경 현황과 거래계좌 등록(변경) 신청서 간 대사내역', 'PLC'),
  ('PP-C-3-1-6', 'ERP 구매업체 등록시 필수정보가 입력되지 않으면 신규 거래처를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-3-2-1', '구매청구서에 대한 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 승인된 구매청구서', 'PLC'),
  ('PP-C-3-2-2', '구매발주서에 대한 전결권자의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 승인된 구매발주서', 'PLC'),
  ('PP-C-3-2-3', '구매발주서는 필수정보가 누락없이 작성되어 일련번호로 문서화됨', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-발주서 등록', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-3-2-4', '장기미발주 현황 모니터링', 'Detective', 'ITDM', 'Monthly', 'Y', 'ERP 생산관리-자재구매관리-발주서 현황', '샘플로 선정한 월에 대한 구매발주현황자료', 'PLC'),
  ('PP-C-3-2-5', '종결된 구매주문에 대하여 발주가 불가능함', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-발주서 등록', '구매발주서 등록시 구매요청서(청구번호) 등록한 화면 캡쳐본', 'PLC'),
  ('PP-C-3-2-6', '납기일자를 초과한 구매발주에 대한 모니터링', 'Detective', 'ITDM', 'Monthly', 'Y', 'ERP 생산관리-자재구매관리-발주서 현황', '샘플로 선정한 월에 대한 구매발주현황자료', 'PLC'),
  ('PP-C-3-2-7', 'ERP 자재 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-품목관리', 'ERP 자재 마스터 상 자재정보 생성 및 변경 권한자 List', 'PLC'),
  ('PP-C-3-2-8', 'ERP 자재 정보 등록 시 필수정보가 입력되지 않으면 신규 자재를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-품목관리', 'Error message 캡쳐화면', 'PLC'),
  ('PP-C-3-2-9', '승인된 구매발주서 없이 입고처리 불가', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-입고 관리', '자재 입고처리 시 구매발주서를 선택하지 않으면 입고처리가 되지 않음을 확인한 화면 캡쳐', 'PLC'),
  ('PP-C-3-3-1', '지급채무전표 생성시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '지급채무(외상매입금, 미지급금)전표 실물전표', 'PLC'),
  ('SD-C-1-1-1', 'ERP 거래처 정보에 대한 승인절차', 'Detective', 'Manual', 'Event driven', 'N', '', '신규거래조사서', 'PLC'),
  ('SD-C-1-1-2', 'ERP 거래처 정보에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', '권한이 없는 인원의 거래처 정보 등록/변경이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-1-1-3', '거래처에 대한 신용평가', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리–사고채권–거래처 신용평가', 'ERP 거래처 현황(현장) List', 'PLC'),
  ('SD-C-1-1-4', '주문 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 영업관리-주문관리-주문서', '권한이 없는 인원의 주문등록/변경 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-1-1-5', '신규 및 변경주문에 대한 승인(가격 및 수량)', 'Preventive', 'Manual', 'Event driven', 'N', '', '1.승인된 출고 품의서(국내철강) 및 수주보고서/profoma invoice(해외철강)
2. ERP상 주문등록내역의 수량/단가/총금액 캡쳐화면
3. 그룹웨어 주문서 캡쳐화면(해외철강)
4. 업체별 할인율표 및 신단가표(국내철강) 또는 제조원가표(해외철강)', 'PLC'),
  ('SD-C-1-1-6', '계약의 완전성', 'Preventive', 'Manual', 'Quarterly', 'N', '', 'ERP 유형별로 분류된 계약서 리스트', 'PLC'),
  ('SD-C-1-1-7', '신규계약에 대한 IFRS 15호 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 IFRS 15 판단 Check List', 'PLC'),
  ('SD-C-1-2-1', '매출에 대한 분석적 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 실적달성현황', 'PLC'),
  ('SD-C-1-2-2', '거래명세서 발행의 적정성 확인', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 영업관리-계산서관리-거래명세서', '거래명세서 처리 캡쳐화면', 'PLC'),
  ('SD-C-1-2-3', '출고 후 미청구된 내역의 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '세금계산서/미발행현황', 'PLC'),
  ('SD-C-1-2-4', '대금청구자료의 정확성 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '출고 List
1.세금계산서/INVOICE(해외철강)', 'PLC'),
  ('SD-C-1-2-5', '대금청구 전산입력에 대한 접근통제', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 영업관리-계산서관리-거래명세서', '권한이 없는 인원의 대금청구에 대한 정보 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-1-2-6', '세금계산서 수정통제', 'Detective', 'Automated', 'Event driven', 'Y', 'ERP2 영업관리-계산서관리-거래명세서', '세금계산서 처리 화면 캡쳐본', 'PLC'),
  ('SD-C-1-2-7', '매출전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '매출전표', 'PLC'),
  ('SD-C-1-3-1', '수금전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP상 수금현황 캡쳐본 또는 입금확인증', 'PLC'),
  ('SD-C-1-3-2', '매출채권 잔고확인 및 회전일검토에 대한 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출채권 및 미수금 보고', 'PLC'),
  ('SD-C-1-3-3', '부실채권 평가 및 보고', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '대손금검토현황', 'PLC'),
  ('SD-C-1-3-4', '매출채권 집합평가에 대한 경영진 리뷰통제', 'Preventive', 'Manual', 'Quarterly', 'N', '', '대손충당금 설정 자료 (대손연령표, ERP상 채권 잔액리스트, 원장 기대손실모형 자료 등)', 'PLC'),
  ('SD-C-1-4-1', '거래처 클레임에 대한 보고통제', 'Detective', 'Manual', 'Event driven', 'N', '', '승인된 사외불만통보서', 'PLC'),
  ('SD-C-1-4-2', '반품시 매출차감조정시 원전표 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '승인된 반품 요청서', 'PLC'),
  ('SD-C-2-1-1', 'ERP 거래처 정보에 대한 승인절차', 'Detective', 'Manual', 'Event driven', 'N', '', '신규거래조사서', 'PLC'),
  ('SD-C-2-1-2', 'ERP 거래처 정보에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', '권한이 없는 인원의 거래처 정보 등록/변경이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-2-1-3', '거래처에 대한 신용평가', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리–사고채권–거래처 신용평가', 'ERP 거래처 현황(현장) List', 'PLC'),
  ('SD-C-2-1-4', '주문 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-주문관리-주문서', '권한이 없는 인원의 주문등록/변경 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-2-1-5', '신규 및 변경주문에 대한 승인(가격 및 수량)', 'Preventive', 'Manual', 'Event driven', 'N', '', 'ERP상 계약등록내역 캡쳐화면', 'PLC'),
  ('SD-C-2-1-6', '계약의 완전성', 'Preventive', 'Manual', 'Quarterly', 'N', '', 'ERP 유형별로 분류된 계약서 리스트', 'PLC'),
  ('SD-C-2-1-7', '신규계약에 대한 IFRS 15호 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 IFRS 15 판단 Check List', 'PLC'),
  ('SD-C-2-2-1', '매출에 대한 분석적 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출달성현황', 'PLC'),
  ('SD-C-2-2-3', '거래명세서 발행 후 미청구된 내역의 검토', 'Detective', 'Manual', 'Event driven', 'N', '', '세금계산서/미발행현황', 'PLC'),
  ('SD-C-2-2-4', '대금청구자료의 정확성 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '세금계산서', 'PLC'),
  ('SD-C-2-2-5', '대금청구 전산입력에 대한 접근통제', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', '권한이 없는 인원의 대금청구에 대한 정보 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-2-2-6', '세금계산서 수정통제', 'Detective', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', '세금계산서 처리 화면 캡쳐본', 'PLC'),
  ('SD-C-2-2-7', '매출전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '매출전표', 'PLC'),
  ('SD-C-2-2-8', '임대기간동안 임대수입금액이 균등하게 매출인식이 되도록 조정', 'Detective', 'Manual', 'Quarterly', 'N', '', '알폼 임대수입명세서(폼국내) 및 시스템폼 임대수입명세서', 'PLC'),
  ('SD-C-2-2-9', 'IFRS 15 조정내역에 대한 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', 'IFRS 15호 체크리스트', 'PLC'),
  ('SD-C-2-3-1', '수금전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP상 수금현황 캡쳐본 또는 입금확인증', 'PLC'),
  ('SD-C-2-3-2', '매출채권 잔고확인 및 회전일검토에 대한 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출채권현황보고서', 'PLC'),
  ('SD-C-2-3-3', '부실채권 평가 및 보고', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '대손금검토현황', 'PLC'),
  ('SD-C-2-3-4', '매출채권 집합평가에 대한 경영진 리뷰통제', 'Preventive', 'Manual', 'Quarterly', 'N', '', '대손충당금 설정 자료 (대손연령표, ERP상 채권 잔액리스트, 원장 기대손실모형 자료 등)', 'PLC'),
  ('SD-C-3-1-1', 'ERP 거래처 정보에 대한 승인절차', 'Detective', 'Manual', 'Event driven', 'N', '', '신규거래조사서', 'PLC'),
  ('SD-C-3-1-2', 'ERP 거래처 정보에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', '권한이 없는 인원의 거래처 정보 등록', 'PLC'),
  ('SD-C-3-1-4', '주문 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-주문관리-주문서', '권한이 없는 인원의 주문등록 
 2.변경 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-3-1-5', '신규 및 변경주문에 대한 승인(가격 및 수량)', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 수주보고서 또는 계약서', 'PLC'),
  ('SD-C-3-1-6', '계약의 완전성', 'Preventive', 'Manual', 'Quarterly', 'N', '', 'ERP 유형별로 분류된 계약서 리스트', 'PLC'),
  ('SD-C-3-1-7', '신규계약에 대한 IFRS 15호 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 IFRS 15 판단 Check List', 'PLC'),
  ('SD-C-3-2-1', '매출에 대한 분석적 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출달성현황', 'PLC'),
  ('SD-C-3-2-2', 'Invoice 및 거래명세서 발행의 적정성 확인', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', 'Invoice  및 거래명세서 처리 캡쳐화면', 'PLC'),
  ('SD-C-3-2-4', '대금청구자료의 정확성 확인', 'Detective', 'Manual', 'Event driven', 'N', '', 'INVOICE', 'PLC'),
  ('SD-C-3-2-5', '대금청구 전산입력에 대한 접근통제', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', '권한이 없는 인원의 대금청구에 대한 정보 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-3-2-6', 'Invoice 수정통제', 'Detective', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-수출관리', 'Invoice 처리 화면 캡쳐본', 'PLC'),
  ('SD-C-3-2-7', '매출전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '매출전표', 'PLC'),
  ('SD-C-3-2-8', '임대기간동안 임대수입금액이 균등하게 매출인식이 되도록 조정', 'Detective', 'Manual', 'Quarterly', 'N', '', '알폼 임대수입명세서(폼해외)', 'PLC'),
  ('SD-C-3-2-9', 'IFRS 15 조정내역에 대한 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', 'IFRS 15호 체크리스트', 'PLC'),
  ('SD-C-3-3-1', '수금전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP상 수금현황 캡쳐본 또는 입금확인증', 'PLC'),
  ('SD-C-3-3-2', '매출채권 잔고확인 및 회전일검토에 대한 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출채권현황보고서', 'PLC'),
  ('SD-C-3-3-3', '부실채권 평가 및 보고', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '대손금검토현황', 'PLC'),
  ('SD-C-3-3-4', '매출채권 집합평가에 대한 경영진 리뷰통제', 'Preventive', 'Manual', 'Quarterly', 'N', '', '대손충당금 설정 자료 (대손연령표, ERP상 채권 잔액리스트, 원장 기대손실모형 자료 등)', 'PLC'),
  ('SD-C-3-4-1', '거래처 클레임에 대한 보고통제', 'Detective', 'Manual', 'Event driven', 'N', '', '승인된 사외불만통보서', 'PLC'),
  ('SD-C-3-4-2', '반품시 매출차감조정시 원전표 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '승인된 반품 요청서', 'PLC'),
  ('SD-C-6-1-1', 'ERP 거래처 정보에 대한 승인절차', 'Detective', 'Manual', 'Event driven', 'N', '', '신규거래조사서', 'PLC'),
  ('SD-C-6-1-2', 'ERP 거래처 정보에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', '권한이 없는 인원의 거래처 정보 등록/변경이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-6-1-3', '거래처에 대한 신용평가', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리–사고채권–거래처 신용평가', 'ERP 거래처 현황(현장) List', 'PLC'),
  ('SD-C-6-1-4', '주문 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-주문관리-주문서', '권한이 없는 인원의 주문등록/변경 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-6-1-5', '신규 및 변경주문에 대한 승인(가격 및 수량)', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 판매품의서 또는 출고의뢰서', 'PLC'),
  ('SD-C-6-1-6', '계약의 완전성', 'Preventive', 'Manual', 'Quarterly', 'N', '', 'ERP 유형별로 분류된 계약서 리스트', 'PLC'),
  ('SD-C-6-1-7', '신규계약에 대한 IFRS 15호 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 IFRS 15 판단 Check List', 'PLC'),
  ('SD-C-6-2-1', '매출에 대한 분석적 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 실적달성현황', 'PLC'),
  ('SD-C-6-2-2', '거래명세서 발행의 적정성 확인', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', '거래명세서 처리 캡쳐화면', 'PLC'),
  ('SD-C-6-2-3', '출고 후 미청구된 내역의 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '세금계산서/미발행현황', 'PLC'),
  ('SD-C-6-2-4', '대금청구자료의 정확성 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '매출체크 List', 'PLC'),
  ('SD-C-6-2-5', '대금청구 전산입력에 대한 접근통제', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', '권한이 없는 인원의 대금청구에 대한 정보 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-6-2-6', '세금계산서 수정통제', 'Detective', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-계산서관리-거래명세서', '세금계산서 처리 화면 캡쳐본', 'PLC'),
  ('SD-C-6-2-7', '매출전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '매출전표', 'PLC'),
  ('SD-C-6-2-8', '임대수입매출 월임대료 산출금액의 정확성 확인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP 임대수입매출전표', 'PLC'),
  ('SD-C-6-2-9', 'IFRS 15 조정내역에 대한 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', 'IFRS 15호 체크리스트', 'PLC'),
  ('SD-C-6-3-1', '수금전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP상 수금현황 캡쳐본 또는 입금확인증', 'PLC'),
  ('SD-C-6-3-2', '매출채권 잔고확인 및 회전일검토에 대한 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출채권 및 미수금 보고', 'PLC'),
  ('SD-C-6-3-3', '부실채권 평가 및 보고', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '대손금검토현황', 'PLC'),
  ('SD-C-6-3-4', '매출채권 집합평가에 대한 경영진 리뷰통제', 'Preventive', 'Manual', 'Quarterly', 'N', '', '대손충당금 설정 자료 (대손연령표, ERP상 채권 잔액리스트, 원장 기대손실모형 자료 등)', 'PLC'),
  ('SD-C-6-4-1', '거래처 클레임에 대한 보고통제', 'Detective', 'Manual', 'Event driven', 'N', '', '승인된 사외불만통보서', 'PLC'),
  ('SD-C-6-4-2', '반품시 매출차감조정시 원전표 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '승인된 반품 요청서', 'PLC'),
  ('SD-C-7-1-1', 'ERP 거래처 정보에 대한 승인절차', 'Detective', 'Manual', 'Event driven', 'N', '', '신규거래조사서', 'PLC'),
  ('SD-C-7-1-2', 'ERP 거래처 정보에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-기본정보-거래처관리', '권한이 없는 인원의 거래처 정보 등록/변경이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-7-1-3', '거래처에 대한 신용평가', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 영업관리–사고채권–거래처 신용평가', 'ERP 거래처 현황(현장) List', 'PLC'),
  ('SD-C-7-1-4', '주문/계약 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 영업관리-주문관리-주문서', '권한이 없는 인원의 주문/계약등록/변경 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-7-1-5', '신규 및 변경주문에 대한 승인(가격 및 수량)', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 계약서 또는 수주확정보고서', 'PLC'),
  ('SD-C-7-1-6', '계약의 완전성', 'Preventive', 'Manual', 'Quarterly', 'N', '', 'ERP 유형별로 분류된 계약서 리스트', 'PLC'),
  ('SD-C-7-1-7', '신규계약에 대한 IFRS 15호 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '승인된 IFRS 15 판단 Check List', 'PLC'),
  ('SD-C-7-2-1', '매출에 대한 분석적 검토', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출달성현황', 'PLC'),
  ('SD-C-7-2-3', '거래명세서 발행 후 미청구된 내역의 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '세금계산서/미발행현황', 'PLC'),
  ('SD-C-7-2-4', '승인된 가격 및 거래조건에 따른 대금 청구', 'Detective', 'Manual', 'Event driven', 'N', '', '세금계산서', 'PLC'),
  ('SD-C-7-2-5', '대금청구 전산입력에 대한 접근통제', 'Preventive', 'Automated', 'Event driven', 'Y', '', '권한이 없는 인원의 대금청구에 대한 정보 입력이 ERP상 입력이 불가능한 화면', 'PLC'),
  ('SD-C-7-2-7', '매출전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '매출전표', 'PLC'),
  ('SD-C-7-2-9', 'IFRS 15 조정내역에 대한 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', 'IFRS 15호 체크리스트', 'PLC'),
  ('SD-C-7-3-1', '수금전표에 대한 승인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP상 수금현황 캡쳐본 또는 입금확인증', 'PLC'),
  ('SD-C-7-3-2', '매출채권 잔고확인 및 회전일검토에 대한 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '승인된 매출채권현황보고서', 'PLC'),
  ('SD-C-7-3-3', '부실채권 평가 및 보고', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '대손금검토현황', 'PLC'),
  ('SD-C-7-3-4', '매출채권 집합평가에 대한 경영진 리뷰통제', 'Preventive', 'Manual', 'Quarterly', 'N', '', '대손충당금 설정 자료 (대손연령표, ERP상 채권 잔액리스트, 원장 기대손실모형 자료 등)', 'PLC'),
  ('PI-C-1-1-1', 'ERP 생산 마스터 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 인사급여관리-인사 기초 관리', 'ERP 인사기초관리상 인원별 Cost Center(급여-계정구분) 생성, 변경 권한자 List', 'PLC'),
  ('PI-C-1-1-3', 'ERP 마스터 정보 등록 시 필수정보가 입력되지 않으면 신규 생산마스터 정보를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 인사급여관리-인사 기초 관리', 'Error Message 캡쳐화면', 'PLC'),
  ('PI-C-1-1-4', 'Cost Center에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '직원별 노무비 구분 검토내역(Cost Center 검토내역)', 'PLC'),
  ('PI-C-1-2-1', '인수자의 검수확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '거래명세표(국내) 또는 수입면장(해외)', 'PLC'),
  ('PI-C-1-2-2', '발주서와 거래명세표 대사 후 입고등록', 'Preventive', 'Manual', 'Event driven', 'N', '', '입고 건에 대한 발주서', 'PLC'),
  ('PI-C-1-2-3', 'ERP상 자재 입고처리에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 생산관리-구매관리-입고관리', 'ERP 프로그램별 사용자 권한 리스트한자 List', 'PLC'),
  ('PI-C-1-2-4', '자재 입고 전표 생성 시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '자재입고전표에 대한 승인 전표 및 증빙', 'PLC'),
  ('PI-C-1-3-1', '실제 생산에 투입된 자재 및 재공품에 대한 확인', 'Preventive', 'Manual', 'Monthly', 'N', '', '샘플로 선정한 월의 재고자산수불부', 'PLC'),
  ('PI-C-1-3-2', '생산실적에 대한 확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '생산실적에 대한 작업발주서 및 작업일보', 'PLC'),
  ('PI-C-1-3-3', 'ERP 생산실적 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 생산관리-생산실적', 'ERP상 생산 실적의 생성 및 변경 권한자 List', 'PLC'),
  ('PI-C-1-3-4', '제품 및 재공품에 대한 일일 순회검사', 'Preventive', 'Manual', 'Daily', 'N', '', '샘플로 선정한 일자의 순회검사일보', 'PLC'),
  ('PI-C-1-3-5', '생산수율에 대한 관리 및 증감 분석', 'Detective', 'Manual', 'Annually', 'N', '', '수율 증감분석 내역', 'PLC'),
  ('PI-C-1-3-6', '수율보고서에 대한 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '수율보고서', 'PLC'),
  ('PI-C-1-3-7', '외주가공비에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 외주가공비 전표 및 품의서', 'PLC'),
  ('PI-C-1-4-1', 'ERP상 상품 입고처리에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP2 생산관리-구매관리-입고관리', 'ERP 사용 권한 리스트', 'PLC'),
  ('PI-C-1-4-2', '상품 입고 전표 생성 시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 상품(매입) 실물전표 및 증빙', 'PLC'),
  ('PI-C-1-4-3', '출고지시에 따른 상품 출고', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 출고번호에 대한 출고품의서(ERP)', 'PLC'),
  ('PI-C-1-5-1', '출고지시에 따른 제품 출고', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 출고번호에 대한 출고품의서', 'PLC'),
  ('PI-C-1-5-2', '공장간 재고 이동에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '재고이송 출고건에 대한 출고증', 'PLC'),
  ('PI-C-1-5-3', '운송중인재고에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 월의 운송중인재고 출고현황', 'PLC'),
  ('PI-C-1-6-1', '재고자산 실사규정 수립 및 검토', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사계획서 (실사규정 포함)', 'PLC'),
  ('PI-C-1-6-2', '재고리스트에 대한 완전성 확인', 'Detective', 'Manual', 'Semi-Annually', 'N', '', '재고실사 리스트 완전성 확인 보고서', 'PLC'),
  ('PI-C-1-6-3', '재고실사 시 파악한 장기재고에 대한 보고서 작성', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 시 파악한 장기재고현황', 'PLC'),
  ('PI-C-1-6-4', '재고실사 보고에 대한 경영진의 검토 및 승인', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 완료보고서', 'PLC'),
  ('PI-C-1-6-5', '재고조정 시 조정 후 수불부상 재고와 실사재고 간 대사', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 완료보고서', 'PLC'),
  ('PI-C-1-7-1', '판매관리비와 제조원가 발생금액에 대한 분석적 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', '판매관리비 및 제조원가 분석적 검토내역', 'PLC'),
  ('PI-C-1-7-2', '재고관리월보와 재고자산수불부집계표 간 분기말 수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 재고자산수불부', 'PLC'),
  ('PI-C-1-7-3', '재고수불부집계표상 제품 출고수량과 재고관리월보상 출고수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 재고자산수불부', 'PLC'),
  ('PI-C-1-7-4', '재고수불부집계표상 원재료 매입수량과 재고관리월보상 원재료 매입수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 원재료 수불부', 'PLC'),
  ('PI-C-1-7-5', '자재 출고량과 생산투입량의 일치', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기에 대한 재고자산수불부', 'PLC'),
  ('PI-C-1-7-6', '원가배부전 비용 집계 금액의 완전성, 정확성 검증', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 원가계산파일(체크리스트)', 'PLC'),
  ('PI-C-1-7-7', '원가계산 결과에 대한 보고 및 승인', 'Preventive', 'Manual', 'Monthly', 'N', '', '샘플로 선정한 월의 손익보고내역', 'PLC'),
  ('PI-C-1-7-8', '제조간접비 배부의 적정성에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 제조간접비 배부적정성 검토내역 및 승인내역(체크리스트)', 'PLC'),
  ('PI-C-1-7-9', '제품 종류별 배부의 적정성에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 제품 종류별 배부적정성 검토내역 및 승인내역(체크리스트)', 'PLC'),
  ('PI-C-1-7-10', '(해당사항 있을시) 재고자산 결산조정 항목 미착품에 대한 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 미착품 전표에 대한 수입증빙(Invoice, BL)', 'PLC'),
  ('PI-C-1-7-11', '현업에서 생성한 비용전표에 대한 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 전표에 대한 품의서 및 품의서에 첨부된 증빙', 'PLC'),
  ('PI-C-1-7-12', '재공품, 제품에 대한 공통비 배부기준 및 배부율에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '재공품, 제품에 대한 공통비 배부기준 및 배부율 검토내역(체크리스트)', 'PLC'),
  ('PI-C-1-7-13', '제품 종류별 재료비, 노무비, 제조간접비 배부기준 및 배부율에 대한 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '제품 종류별 재료비, 노무비, 제조간접비 배부기준 및 배부율 검토내역(체크리스트)', 'PLC'),
  ('PI-C-1-7-14', '원가 배부금액 확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '분기별 원가계산파일(체크리스트)', 'PLC'),
  ('PI-C-1-7-15', '저가법(NRV)평가에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 NRV평가 계산파일 및 계산 기초 데이터에 대한 근거자료', 'PLC'),
  ('PI-C-2-1-1', 'ERP 생산 마스터 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', '1) ERP 생산관리- BOM
2) ERP 인사급여관리-인사 기초 관리', 'BOM(이론중량) 마스터 생성, 변경 권한자 List', 'PLC'),
  ('PI-C-2-1-2', 'ERP 생산 정보(BOM(이론중량)) 신규등록/변경 시 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플 건에 대한 마스터 등록/변경 신청서', 'PLC'),
  ('PI-C-2-1-3', 'ERP 마스터 정보 등록 시 필수정보가 입력되지 않으면 신규 생산마스터 정보를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', '1) ERP 생산관리- BOM
2) ERP 인사급여관리-인사 기초 관리', 'Error Message 캡쳐화면', 'PLC'),
  ('PI-C-2-1-4', 'Cost Center에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '직원별 노무비 구분 검토내역(Cost Center 검토내역)', 'PLC'),
  ('PI-C-2-1-5', 'BOM(이론중량)에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '연 1회 BOM(이론중량) 검토내역', 'PLC'),
  ('PI-C-2-2-1', '인수자의 검수확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '거래명세표(국내) 또는 수입면장(해외)', 'PLC'),
  ('PI-C-2-2-2', '발주서와 거래명세표 대사 후 입고등록', 'Preventive', 'Manual', 'Event driven', 'N', '', '입고 건에 대한 발주서', 'PLC'),
  ('PI-C-2-2-3', 'ERP상 자재 입고처리에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-입고관리', 'ERP 프로그램별 사용자 권한 리스트', 'PLC'),
  ('PI-C-2-2-4', '자재 입고 전표 생성 시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '자재입고전표에 대한 승인 전표 및 증빙', 'PLC'),
  ('PI-C-2-3-2', '생산실적에 대한 확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '생산현황에 대한 작업발주서 및 작업일보', 'PLC'),
  ('PI-C-2-3-3', 'ERP 생산실적 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-생산실적', 'ERP상 생산 실적의 생성 및 변경 권한자 List', 'PLC'),
  ('PI-C-2-3-4', '생산완료된 제품에 대한 품질검사', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 일자의 품질검사보고서 (폼)', 'PLC'),
  ('PI-C-2-3-5', '생산수율에 대한 관리 및 증감 분석', 'Detective', 'Manual', 'Annually', 'N', '', '수율 증감분석 내역', 'PLC'),
  ('PI-C-2-3-6', '수율보고서에 대한 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '수율보고서', 'PLC'),
  ('PI-C-2-3-7', '외주가공비에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 외주가공비 전표 및 품의서', 'PLC'),
  ('PI-C-2-4-1', 'ERP상 상품 입고처리에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-생산발주 통합관리', 'ERP 사용 권한 리스트', 'PLC'),
  ('PI-C-2-4-2', '상품 입고 전표 생성 시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 상품(매입) 실물전표 및 증빙', 'PLC'),
  ('PI-C-2-4-3', '출고지시에 따른 상품 출고', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 출고번호에 대한 출고송장', 'PLC'),
  ('PI-C-2-5-1', '출고지시에 따른 제품 출고', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 출고번호에 대한 출고품의서', 'PLC'),
  ('PI-C-2-5-2', '공장간 재고 이동에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '재고이송 출고건에 대한 출고증', 'PLC'),
  ('PI-C-2-5-3', '운송중인재고에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 월의 운송중인재고 출고현황', 'PLC'),
  ('PI-C-2-6-1', '재고자산 실사규정 수립 및 검토', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사계획서 (실사규정 포함)', 'PLC'),
  ('PI-C-2-6-2', '재고리스트에 대한 완전성 확인', 'Detective', 'Manual', 'Semi-Annually', 'N', '', '재고실사 리스트 완전성 확인 보고서', 'PLC'),
  ('PI-C-2-6-3', '재고실사 시 파악한 장기재고에 대한 보고서 작성', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 시 파악한 장기재고현황', 'PLC'),
  ('PI-C-2-6-4', '재고실사 보고에 대한 경영진의 검토 및 승인', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 완료보고서', 'PLC'),
  ('PI-C-2-6-5', '재고조정 시 조정 후 수불부상 재고와 실사재고 간 대사', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 완료보고서', 'PLC'),
  ('PI-C-2-6-6', '무상사급재고에 대한 확인', 'Preventive', 'Manual', 'Monthly', 'N', '', '샘플로 선정한 월의 모든 무상사급처에 대한 원자재 투입대비 생산량 분석 보고서', 'PLC'),
  ('PI-C-2-6-8', '주요 재고자산에 대한 월별 실사', 'Preventive', 'Manual', 'Monthly', 'N', '', '샘플로 선정한 월의 원재료, 재공품, A급 규격 대기품, 규격 제품에 대한 월별 실사보고서', 'PLC'),
  ('PI-C-2-6-9', '비규격 제품에 대한 인수증 확인', 'Detective', 'Manual', 'Event driven', 'N', '', '기말 ERP 비규격 제품 미진행현황(포장) List', 'PLC'),
  ('PI-C-2-7-1', '판매관리비와 제조원가 발생금액에 대한 분석적 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', '판매관리비 및 제조원가 분석적 검토내역', 'PLC'),
  ('PI-C-2-7-2', '재고관리월보와 재고자산수불부집계표 간 분기말 수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 재고자산수불부', 'PLC'),
  ('PI-C-2-7-3', '소재사업부 재고수불부 상 제품 출고 수량과 폼사업부 원자재 수불부 상 원자재 입고 수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 소재사업부 제품 수불부', 'PLC'),
  ('PI-C-2-7-4', '재고수불부집계표상 원재료 매입수량과 재고관리월보상 원재료 매입수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 소재사업부 원재료 수불부', 'PLC'),
  ('PI-C-2-7-6', '원가배부전 비용 집계 금액의 완전성, 정확성 검증', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 원가계산파일(체크리스트)', 'PLC'),
  ('PI-C-2-7-7', '원가계산 결과에 대한 보고 및 승인', 'Preventive', 'Manual', 'Monthly', 'N', '', '샘플로 선정한 월의 손익보고내역', 'PLC'),
  ('PI-C-2-7-8', '제조간접비 배부의 적정성에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 제조간접비 배부적정성 검토내역 및 승인내역(체크리스트)', 'PLC'),
  ('PI-C-2-7-9', '제품 종류별 배부의 적정성에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 제품 종류별 배부적정성 검토내역 및 승인내역(체크리스트)', 'PLC'),
  ('PI-C-2-7-11', '현업에서 생성한 비용전표에 대한 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 전표에 대한 품의서 및 품의서에 첨부된 증빙', 'PLC'),
  ('PI-C-2-7-12', '재공품, 제품에 대한 공통비 배부기준 및 배부율에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '재공품, 제품에 대한 공통비 배부기준 및 배부율 검토내역(체크리스트)', 'PLC'),
  ('PI-C-2-7-13', '제품 종류별 재료비, 노무비, 제조간접비 배부기준 및 배부율에 대한 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '제품 종류별 재료비, 노무비, 제조간접비 배부기준 및 배부율 검토내역(체크리스트)', 'PLC'),
  ('PI-C-2-7-14', '원가 배부금액 확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '제조원가명세서', 'PLC'),
  ('PI-C-2-7-15', '저가법(NRV)평가에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 NRV평가 계산파일 및 계산 기초 데이터에 대한 근거자료', 'PLC'),
  ('PI-C-3-1-1', 'ERP 생산 마스터 정보 등록/변경 생성 권한에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 인사급여관리-인사 기초 관리', 'ERP 인사기초관리상 인원별 Cost Center(급여-계정구분) 생성, 변경 권한자 List', 'PLC'),
  ('PI-C-3-1-3', 'ERP 마스터 정보 등록 시 필수정보가 입력되지 않으면 신규 생산마스터 정보를 등록할 수 없음', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 인사급여관리-인사 기초 관리', 'Error Message 캡쳐화면', 'PLC'),
  ('PI-C-3-1-4', 'Cost Center에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '직원별 노무비 구분 검토내역(Cost Center 검토내역)', 'PLC'),
  ('PI-C-3-2-1', '인수자의 검수확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '거래명세표(국내) 또는 수입면장(해외)', 'PLC'),
  ('PI-C-3-2-2', '발주서와 거래명세표 대사 후 입고등록', 'Preventive', 'Manual', 'Event driven', 'N', '', '입고 건에 대한 발주서', 'PLC'),
  ('PI-C-3-2-3', 'ERP상 자재 입고처리에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-입고관리', 'ERP 프로그램별 사용자 권한 리스트', 'PLC'),
  ('PI-C-3-2-4', '자재 입고 전표 생성 시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '자재입고전표에 대한 승인 전표 및 증빙', 'PLC'),
  ('PI-C-3-3-1', '실제 생산에 투입된 자재에 대한 확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '자재불출(사용실적) 현황', 'PLC'),
  ('PI-C-3-3-2', '생산실적에 대한 확인', 'Preventive', 'Manual', 'Event driven', 'N', '', '생산현황에 대한 작업발주서 및 작업일보', 'PLC'),
  ('PI-C-3-3-3', 'ERP 생산실적 입력에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-생산실적', 'ERP상 생산 실적의 생성 및 변경 권한자 List', 'PLC'),
  ('PI-C-3-3-4', '생산완료된 제품에 대한 품질검사', 'Preventive', 'Manual', 'Event driven', 'N', '', '생산현황에 대한 제품검사성적서', 'PLC'),
  ('PI-C-3-3-5', '생산수율에 대한 관리 및 증감 분석', 'Detective', 'Manual', 'Event driven', 'N', '', '수율 증감분석 내역', 'PLC'),
  ('PI-C-3-3-6', '수율보고서에 대한 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '수율보고서', 'PLC'),
  ('PI-C-3-3-7', '외주가공비에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 외주가공비 전표 및 품의서', 'PLC'),
  ('PI-C-3-4-1', 'ERP상 상품 입고처리에 대한 접근제한', 'Preventive', 'Automated', 'Event driven', 'Y', 'ERP 생산관리-자재구매관리-입고관리', 'ERP 사용 권한 리스트', 'PLC'),
  ('PI-C-3-4-2', '상품 입고 전표 생성 시 전결권자 및 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 상품(매입) 실물전표 및 증빙', 'PLC'),
  ('PI-C-3-4-3', '출고지시에 따른 상품 출고', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 출고번호에 대한 출고품의서(ERP)', 'PLC'),
  ('PI-C-3-5-1', '출고지시에 따른 제품 출고', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 출고번호에 대한 출고품의서', 'PLC'),
  ('PI-C-3-5-2', '공장간 재고 이동에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '재고이송 출고건에 대한 출고증', 'PLC'),
  ('PI-C-3-5-3', '운송중인재고에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 월의 운송중인재고 출고현황', 'PLC'),
  ('PI-C-3-6-1', '재고자산 실사규정 수립 및 검토', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사계획서 (실사규정 포함)', 'PLC'),
  ('PI-C-3-6-2', '재고리스트에 대한 완전성 확인', 'Detective', 'Manual', 'Semi-Annually', 'N', '', '재고실사 리스트 완전성 확인 보고서', 'PLC'),
  ('PI-C-3-6-3', '재고실사 시 파악한 장기재고에 대한 보고서 작성', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 시 파악한 장기재고현황', 'PLC'),
  ('PI-C-3-6-4', '재고실사 보고에 대한 경영진의 검토 및 승인', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 완료보고서', 'PLC'),
  ('PI-C-3-6-5', '재고조정 시 조정 후 수불부상 재고와 실사재고 간 대사', 'Preventive', 'Manual', 'Semi-Annually', 'N', '', '재고실사 완료보고서', 'PLC'),
  ('PI-C-3-6-6', '무상사급재고에 대한 확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 무상사급 재고에 대한 실사보고서', 'PLC'),
  ('PI-C-3-7-1', '판매관리비와 제조원가 발생금액에 대한 분석적 검토', 'Detective', 'Manual', 'Quarterly', 'N', '', '판매관리비 및 제조원가 분석적 검토내역', 'PLC'),
  ('PI-C-3-7-2', '재고관리월보와 재고자산수불부집계표 간 분기말 수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 재고자산수불부', 'PLC'),
  ('PI-C-3-7-3', '재고수불부집계표상 제품 출고수량과 재고관리월보상 출고수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 재고자산수불부', 'PLC'),
  ('PI-C-3-7-4', '재고수불부집계표상 원재료 매입수량과 재고관리월보상 원재료 매입수량 대사확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 원재료 수불부', 'PLC'),
  ('PI-C-3-7-5', '자재 출고량과 생산투입량의 일치', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기에 대한 재고자산수불부', 'PLC'),
  ('PI-C-3-7-6', '원가배부전 비용 집계 금액의 완전성, 정확성 검증', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 원가계산파일(체크리스트)', 'PLC'),
  ('PI-C-3-7-7', '원가계산 결과에 대한 보고 및 승인', 'Preventive', 'Manual', 'Monthly', 'N', '', '샘플로 선정한 월의 손익보고내역', 'PLC'),
  ('PI-C-3-7-8', '제조간접비 배부의 적정성에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 제조간접비 배부적정성 검토내역 및 승인내역(체크리스트)', 'PLC'),
  ('PI-C-3-7-9', '제품 종류별 배부의 적정성에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 제품 종류별 배부적정성 검토내역 및 승인내역(체크리스트)', 'PLC'),
  ('PI-C-3-7-10', '(해당사항 있을시) 재고자산 결산조정 항목 미착품에 대한 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 미착품 전표에 대한 수입증빙(Invoice, BL)', 'PLC'),
  ('PI-C-3-7-11', '현업에서 생성한 비용전표에 대한 회계팀의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정한 전표에 대한 품의서 및 품의서에 첨부된 증빙', 'PLC'),
  ('PI-C-3-7-12', '재공품, 제품에 대한 공통비 배부기준 및 배부율에 대한 주기적 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '재공품, 제품에 대한 공통비 배부기준 및 배부율 검토내역(체크리스트)', 'PLC'),
  ('PI-C-3-7-13', '제품 종류별 재료비, 노무비, 제조간접비 배부기준 및 배부율에 대한 검토 및 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '제품 종류별 재료비, 노무비, 제조간접비 배부기준 및 배부율 검토내역(체크리스트)', 'PLC'),
  ('PI-C-3-7-14', '원가 배부금액 확인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '제조원가명세서', 'PLC'),
  ('PI-C-3-7-15', '저가법(NRV)평가에 대한 검토 및 승인', 'Preventive', 'Manual', 'Quarterly', 'N', '', '샘플로 선정한 분기의 NRV평가 계산파일 및 계산 기초 데이터에 대한 근거자료', 'PLC'),
  ('TR-C-1-1-1', '가수금 정산', 'Detective', 'Manual', 'Daily', 'N', '', '기타입금 내역의 승인전표', 'PLC'),
  ('TR-C-1-1-2', '입금 전표의 승인', 'Detective', 'Manual', 'Daily', 'N', '', '입금 승인전표', 'PLC'),
  ('TR-C-1-2-1', '받을어음 전표의 승인', 'Detective', 'Manual', 'Daily', 'N', '', '받을어음 수금 승인전표', 'PLC'),
  ('TR-C-1-2-2', '월별 부도어음 모니터링', 'Preventive', 'Manual', 'Monthly', 'N', '', '월별 받을어음(지급일자별) 현황', 'PLC'),
  ('TR-C-1-3-1', '회사명의 계좌 개설 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', 'ERP 계좌등록 조회화면', 'PLC'),
  ('TR-C-1-3-2', '계좌 개설시 법인인감 날인 통제', 'Preventive', 'Manual', 'Event driven', 'N', '', '법인인감사용대장 사본', 'PLC'),
  ('TR-C-1-3-3', '계좌 해지 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '계좌 해지 관련 승인문서', 'PLC'),
  ('TR-C-1-4-1', '일일자금실적의 검토 및 승인', 'Detective', 'Manual', 'Daily', 'N', '', '일일 자금계획', 'PLC'),
  ('TR-C-1-4-2', '자금실적과 ERP 현금및현금등가물 대사 및 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '월말 자금실적', 'PLC'),
  ('TR-C-1-4-3', '은행계좌 분기별자금실사', 'Detective', 'Manual', 'Quarterly', 'N', '', '자금 분기 감사철의 회사 명세자료(계정별 잔액 리스트 등)', 'PLC'),
  ('TR-C-1-5-1', '자금집행의 승인', 'Preventive', 'Manual', 'Daily', 'N', '', '지급 승인전표', 'PLC'),
  ('TR-C-1-5-2', '자금이체 업무분장(SOD)', 'Detective', 'Manual', 'Daily', 'N', '', '자금이체 업무분장도', 'PLC'),
  ('TR-C-1-5-3', '거래처 계좌 등록 및 변경 신청서 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', 'ERP 거래처별 계좌승인 조회화면', 'PLC'),
  ('TR-C-1-6-1', '경비 비용지출에 대한 결제요청 문서화 및 비용타당성 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '경비 비용 승인전표', 'PLC'),
  ('TR-C-1-6-2', '미상신 법인카드 사용의 완전성 확인', 'Detective', 'Manual', 'Event driven', 'N', '', 'ERP 법인카드 사용리스트(매입일자 기준, 전표 미처리 조회화면)', 'PLC'),
  ('TR-C-1-6-3', '법인카드 사용현황 및 법인카드 결제전표의 승인', 'Detective', 'Manual', 'Monthly', 'N', '', '법인카드 결제(결제대금 지급) 전표', 'PLC'),
  ('TR-C-1-7-1', '투자자산의 취득 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '투자자산 취득품의서', 'PLC'),
  ('TR-C-1-7-2', '금융상품 회계처리 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '금융상품 취득 품의서', 'PLC'),
  ('TR-C-1-7-3', '선물환 취득', 'Preventive', 'Manual', 'Event driven', 'N', '', '선물환 약정 품의서', 'PLC'),
  ('TR-C-1-7-4', '금융상품 취득/만기 전표 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '금융상품 취득 또는 만기전표 및 증빙', 'PLC'),
  ('TR-C-1-7-5', '대여금 및 회수계획 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '대여금 전표', 'PLC'),
  ('TR-C-1-8-1', 'ERP 금융상품 정보로 이자수익 자동계산', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 회계관리-자금관리', 'ERP상 이자수익 계산 내역 화면', 'PLC'),
  ('TR-C-1-8-2', '이자수익 및 미수이자의 승인', 'Preventive', 'Manual', 'Monthly', 'N', '', '미수수익 전표', 'PLC'),
  ('TR-C-1-8-3', '익월초 미수수익 자동 역분개', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 회계관리-전표-결산전표복사((-)전표생성)', '미수수익(이자수익) 전표', 'PLC'),
  ('TR-C-1-8-4', '투자손익 전표의 승인', 'Detective', 'Manual', 'Quarterly', 'N', '', '투자이익전표', 'PLC'),
  ('TR-C-1-8-5', '금융상품 분기별자금실사', 'Detective', 'Manual', 'Quarterly', '', '', '자금 분기 감사철의 회사 명세자료(계정별 잔액 리스트 등)', 'PLC'),
  ('TR-C-1-8-6', '투자자산 해지/매각 검토 및 승인', 'Detective', 'Manual', 'Event driven', 'N', '', '투자자산(지분상품 및 채무상품) 해지/매각 전표', 'PLC'),
  ('TR-C-1-9-1', '신규차입/사채발행의 검토 및 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '신규 은행차입 또는 사채발행 전표', 'PLC'),
  ('TR-C-1-9-2', '차입금/사채 ERP정보 적발통제', 'Detective', 'Manual', 'Monthly', 'N', '', '월별 ERP 차입금/사채 현황', 'PLC'),
  ('TR-C-1-9-3', '차입금/사채 상환 전표 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '차입금 또는 사채 상환 전표', 'PLC'),
  ('TR-C-1-9-4', 'ERP 차입금 정보를 기초로 이자비용 자동계산', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 회계관리-차입금 관리', 'ERP상 이자비용 계산 내역 화면', 'PLC'),
  ('TR-C-1-9-5', '이자비용 및 미지급이자의 승인', 'Preventive', 'ITDM', 'Monthly', 'Y', 'ERP 회계관리-차입금 관리', '미지급비용(이자비용) 전표', 'PLC'),
  ('TR-C-1-9-6', '익월초 미지급이자 자동 역분개', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 회계관리-전표-결산전표복사((-)전표생성)', '미지급비용(이자비용) 인식 결산전표', 'PLC'),
  ('TR-C-1-9-7', '사채할인발행차금 회계처리 및 승인', 'Preventive', 'ITDM', 'Monthly', 'Y', 'ERP 회계관리-차입금 관리', '사채할인발행차금 전표', 'PLC'),
  ('TR-C-1-9-8', '차입금/사채 분기별 자금실사', 'Detective', 'Manual', 'Quarterly', 'N', '', '자금 분기 감사철의 회사 명세자료(계정별 잔액 리스트 등)', 'PLC'),
  ('TR-C-1-9-9', '전환사채 전환시 회계처리 검토 및 전표 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '전환사채 감소 전표', 'PLC'),
  ('TR-C-1-9-10', '파생상품 평가손익 전표승인 ', 'Preventive', 'Manual', 'Quarterly', 'N', '', '파생상품 평가손익 전표', 'PLC'),
  ('TR-C-1-10-1', '담보등록시 적절한 승인권자의 승인', 'Preventive', 'Manual', 'Event driven', 'N', '', '신규 담보제공 품의서', 'PLC'),
  ('TR-C-1-10-2', '담보관련 약정사항의 정합성 확인', 'Detective', 'Manual', 'Quarterly', 'N', '', '샘플로 선정된 분기의 담보현황', 'PLC'),
  ('TR-C-1-10-3', '지급보증요청 내역 검토', 'Preventive', 'Manual', 'Event driven', 'N', '', '샘플로 선정된 지급보증발행리스트', 'PLC'),
  ('TR-C-1-10-4', '지급보증 관련 모니터링 및 약정사항의 정합성 확인', 'Detective', 'ITDM', 'Quarterly', 'Y', 'ERP 회계관리-지급보증관리', '샘플로 선정된 분기의 지급보증현황', 'PLC'),
  ('TR-C-2-1-1', 'PO문서(수주보고서, 계약서) 및 수입신용장개설의뢰문서 내역에 대한 정확성 검토 및 승인', 'Preventive', 'Manual', 'Event Driven', 'N', '', '수입신용장 개설의뢰 협조전', 'PLC'),
  ('TR-C-2-1-2', 'L/C 대금 지급시 금액 적정성에 대한 검토 및 승인
', 'Preventive', 'Manual', 'Event Driven', 'N', '', '수입신용장 대금 지급 관련 승인문서', 'PLC'),
  ('TR-C-2-1-3', '거래은행으로부터 수령한 SIGHT L/C 원장과 ERP상 잔액을 대사하여 추가 발생가능 우발채무 검토
', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 회계관리-보조관리-수입LC관리대장', '샘플로 선정된 분기의 수입LC 관리대장', 'PLC'),
  ('PR-C-1-1-1', 'ERP 인사정보(인원변경)에 대한 승인', 'Preventive', 'Manual', 'Event Driven', 'N', '', 'ERP 인사급여관리 인원변경 변동 Log', 'PLC'),
  ('PR-C-1-1-2', 'ERP 인사정보(급여변경)에 대한 승인', 'Preventive', 'Manual', 'Event Driven', 'N', '', 'ERP 인사급여관리 연봉/일급내역 List', 'PLC'),
  ('PR-C-1-1-3', 'ERP 인사정보와 급여대장 인원과의 대사', 'Detective', 'Manual', 'Monthly', 'N', '', '월별급여대장', 'PLC'),
  ('PR-C-1-1-4', 'ERP 인사정보 일괄변경에 대한 승인', 'Detective', 'Manual', 'Event Driven', 'N', '', '회사 내의 정책(연봉/호봉표)이나 급여 관련 법령 (근로기준법, 세율 등) 변경 문서', 'PLC'),
  ('PR-C-1-2-1', '근태기록의 주기적 검토', 'Preventive', 'Manual', 'Weekly', 'N', '', '세콤 출퇴근 기록', 'PLC'),
  ('PR-C-1-2-2', '연장근무 작성분 승인', 'Preventive', 'Manual', 'Event Driven', 'N', '', '급여대장', 'PLC'),
  ('PR-C-1-2-3', '연차사용에 관한 전결권자의 승인과 타당성 검증', 'Preventive', 'Manual', 'Event Driven', 'N', '', 'ERP상 근태관리(휴가신청) List', 'PLC'),
  ('PR-C-1-3-1', '급여계산의 자동화', 'Preventive', 'Automated', 'Monthly', 'Y', 'ERP 인사급여관리-급여관리', 'ERP상 급여 계산 내역 화면', 'PLC'),
  ('PR-C-1-3-2', '월별 급여변동분석내역', 'Detective', 'Manual', 'Monthly', 'N', '', '월별 임금지급내역(급여변동분석내역)', 'PLC'),
  ('PR-C-1-3-3', '급여계산 내역 및 급여 전표의 승인', 'Detective', 'ITDM', 'Monthly', 'Y', '1) ERP 인사급여관리-급여관리
2) ERP 인사급여관리-인사급여자동전표', '급여대장', 'PLC'),
  ('PR-C-1-4-1', '복리후생비 지출에 대한 검토 및 승인', 'Preventive', 'Manual', 'Event Driven', 'N', '', '복리후생비 지급 관련 승인문서', 'PLC'),
  ('PR-C-1-4-2', '복리후생비 회계처리', 'Preventive', 'Manual', 'Event Driven', 'N', '', '복리후생비 전표', 'PLC'),
  ('PR-C-1-5-1', '연차수당의 자동계산', 'Preventive', 'Automated', 'Event Driven', 'Y', 'ERP 인사급여관리-연월차관리', 'ERP 연차정산내역', 'PLC'),
  ('PR-C-1-5-2', '연차충당부채 계산에 대한 검토 및 승인_EUC', 'Preventive', 'Manual', 'Quarterly', 'N', '', '연차수당 계산파일', 'PLC'),
  ('PR-C-1-5-3', '연차충당부채 전표 검토 및 승인 ', 'Preventive', 'Manual', 'Quarterly', 'N', '', '연월차수당 설정 전표', 'PLC'),
  ('PR-C-2-1-1', '퇴직금 전표 검토 및 승인_퇴직급여충당부채 반제', 'Preventive', 'Manual', 'Event Driven', 'N', '', '퇴직급여충당부채 반제전표', 'PLC'),
  ('PR-C-2-1-2', '퇴직금 전표 검토 및 승인_퇴직급여 미지급비용반제', 'Preventive', 'Manual', 'Event Driven', 'N', '', '퇴직금 지급전표(미지급비용 반제전표)', 'PLC'),
  ('PR-C-2-2-1', '계리평가 기초제공정보 정확성/완전성 검토', 'Preventive', 'ITDM', 'Quarterly', 'Y', 'ERP 인사급여관리-계리평가_재직자명부,퇴직자명부', '계리평가 기초자료(재직자 명부)', 'PLC'),
  ('PR-C-2-2-2', '계리평가보고서에 대한 상위권자의 검토 및 승인', 'Detective', 'Manual', 'Quarterly', 'N', '', '계리평가보고서', 'PLC'),
  ('PR-C-2-2-3', '계리평가보고서와 확정급여부채, 장기종업원급여충당부채 원장 대사', 'Detective', 'Manual', 'Quarterly', 'N', '', '계리평가보고서', 'PLC'),
  ('PR-C-2-3-1', '사외적립자산 추가불입액 결정의 승인', 'Preventive', 'Manual', 'Annually', 'N', '', '퇴직연금운용자산 불입 품의서', 'PLC'),
  ('PR-C-2-3-2', '사외적립자산 평가금액 전표 승인', 'Preventive', 'Manual', 'Monthly', 'N', '', '사외적립자산 평가 승인전표', 'PLC')
ON CONFLICT (ctrl_code) DO NOTHING;
